[package]
name = "optimized"
version = "0.1.0"
publish = false

[[bin]]
name = "test_max_level_features"
path = "main.rs"

[dependencies.log]
path = ".."
features = ["max_level_debug", "release_max_level_info"]
